version: '2'
services:
  opensearch:
    image: opensearchproject/opensearch:2.0.0
    container_name: opensearch
    hostname: opensearch
    environment:
          - cluster.name=opensearch
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
          memlock:
            soft: -1
            hard: -1
    command: opensearch -Ehttp.cors.enabled=true
    volumes:
          - /opensearch/data

  hbase:
    image: hyness/hbase-rest-standalone
    hostname: hbase
    volumes:
     - /data/hbase
     - /data/zookeeper

  foxtrot-server:
    depends_on:
     - opensearch
     - hbase
    container_name: foxtrot_server
    build: .
    ports:
     - "17000:17000"
     - "17001:17001"
     - "5701:5701"
    volumes:
     - /var/log/foxtrot-server
    environment:
     - HOST=localhost
     - OPENSEARCH_HOST=opensearch
     - OPENSEARCH_PORT=9300
     - OPENSEARCH_CLUSTER_NAME=opensearch
     - OPENSEARCH_TABLE_NAME_PREFIX=foxtrot
     - OPENSEARCH_PORT="9200"
     - OPENSEARCH_PROTOCOL=http
     - HBASE_TABLE_NAME=foxtrot
     - HBASE_ZOOKEEPER_QUORUM=hbase
     - HBASE_ZOOKEEPER_CLIENT_PORT=2181
     - HAZELCAST_CLUSTER_NAME=foxtrot
     - GOOGLE_CALLBACK_HOST_PORT=localhost:17000
     - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
     - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
     - GOOGLE_SECURE_ENDPOINT=false
     - DISCOVERY_TYPE=foxtrot_simple
     - SWAGGER_SCHEME="http"
     - PRIVATE_KEY="6/Qh1eLvF7cGJEgH1wIMYErIpi0d8Kqt5wHKw/o5iFbhfziKiux03HfFihO2+f5FKpsjk1D7UmgdAWQsY966WkyAsyo22m4g+C+rNCwMUD/UM2qop7JZBDEkgWpwK8jpxOTpYUnaNsiBaBsadoZCQ+Ns/d8RrS7QPAW+1PETbdFfo+fPW0/Sm8RUmMKkc9jJ6bhuSpFH3q/bWoyPZnj7geYQQIkgmQv9jXaszw=="
     - STARTUP_DELAY=15
     - CONFIG_PATH=/config/docker-gauth.yml

