version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.8
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
          - cluster.name=elasticsearch
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
          memlock:
            soft: -1
            hard: -1
    command: elasticsearch -Ehttp.cors.enabled=true
    volumes:
          - /elasticsearch/data
    ports:
     - "9200:9200"
     - "9300:9300"

  hbase:
    image: hyness/hbase-rest-standalone
    hostname: hbase
    ports:
     - "2181:2181"
     - "8080:8080"
     - "16000:16000"
     - "16010:16010"
     - "16020:16020"
     - "16030:16030"
    volumes:
     - /data/hbase
     - /data/zookeeper

  foxtrot-server:
    depends_on:
     - elasticsearch
     - hbase
    container_name: foxtrot_server
    build: .
    ports:
     - "17000:17000"
     - "17001:17001"
     - "5701:5701"
    volumes:
     - /var/log/foxtrot-server
    environment:
     - HOST=localhost
     - ELASTICSEARCH_HOST=elasticsearch
     - ELASTICSEARCH_CLUSTER_NAME=elasticsearch
     - ELASTICSEARCH_TABLE_NAME_PREFIX=foxtrot
     - ELASTICSEARCH_PORT="9200"
     - ELASTICSEARCH_PROTOCOL=http
     - HBASE_TABLE_NAME=foxtrot
     - HBASE_ZOOKEEPER_QUORUM=hbase
     - HBASE_ZOOKEEPER_CLIENT_PORT=2181
     - HAZELCAST_CLUSTER_NAME=foxtrot
     - AUTH_ENABLED=true
     - GOOGLE_CALLBACK_HOST_PORT=localhost:17000
     - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
     - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
     - GOOGLE_SECURE_ENDPOINT=false
     - DISCOVERY_TYPE=foxtrot_simple
     - SWAGGER_SCHEME="http"
     - PRIVATE_KEY="6/Qh1eLvF7cGJEgH1wIMYErIpi0d8Kqt5wHKw/o5iFbhfziKiux03HfFihO2+f5FKpsjk1D7UmgdAWQsY966WkyAsyo22m4g+C+rNCwMUD/UM2qop7JZBDEkgWpwK8jpxOTpYUnaNsiBaBsadoZCQ+Ns/d8RrS7QPAW+1PETbdFfo+fPW0/Sm8RUmMKkc9jJ6bhuSpFH3q/bWoyPZnj7geYQQIkgmQv9jXaszw=="
