#! /bin/bash -e

PKG_NAME=foxtrot-server

function die()
{
        echo "Error: $1" >&2
        exit 1
}

[ -z "$LOCAL_DIR" ] && die "No LOCAL_DIR dir specified"
[ -z "$TARGET" ] && die "No package target specified"
[ -z "$INSTALL_BASE" ] && die "No install base specified"
[ -z "$PACKAGE" ] && die "No package name specified"
[ ! -d "$LOCAL_DIR" ] && die "$LOCAL_DIR does not exist"

case "$TARGET" in
        nm) ENV=nm;;
        stagech) ENV=stagech;;
esac
[ -z "$ENV" ] && die "Invalid target: $TARGET"

cd $LOCAL_DIR
DEB_DIR=deb
if [ -e $DEB_DIR ]; then
    rm -rf $DEB_DIR
fi

mkdir $DEB_DIR
mkdir -p $DEB_DIR/etc/$PKG_NAME
mkdir -p $DEB_DIR/var/lib/$PKG_NAME
mkdir -p $DEB_DIR/etc/init.d
mkdir -p $DEB_DIR/var/log/flipkart/foxtrot-server
mkdir -p $DEB_DIR/DEBIAN

cp DEBIAN/foxtrot-server/control      $DEB_DIR/DEBIAN/control
cp DEBIAN/foxtrot-server/postinst     $DEB_DIR/DEBIAN/postinst
cp DEBIAN/foxtrot-server/postrm       $DEB_DIR/DEBIAN/postrm
cp DEBIAN/foxtrot-server/preinst      $DEB_DIR/DEBIAN/preinst
cp DEBIAN/foxtrot-server/prerm        $DEB_DIR/DEBIAN/prerm
cp DEBIAN/foxtrot-server/$PKG_NAME    $DEB_DIR/etc/init.d/$PKG_NAME
chmod -R 777 $DEB_DIR/var/log/flipkart/foxtrot-server

/usr/share/fk-ops-maven2/bin/mvn clean install -DskipTests
cd foxtrot-server
/usr/share/fk-ops-maven2/bin/mvn package -DskipTests
cd ..

if [ "$ENV" = "stagech" ]; then
    cp config/foxtrot-server/stagech.yml $DEB_DIR/etc/$PKG_NAME/config.yml
fi
if [ "$ENV" = "nm" ]; then
    cp config/foxtrot-server/nm.yml $DEB_DIR/etc/$PKG_NAME/config.yml
fi

cp foxtrot-server/target/foxtrot-server-0.1.jar $DEB_DIR/var/lib/$PKG_NAME/foxtrot-server.jar
