package com.flipkart.foxtrot.core.exception;

/**
 * Created by rishabh.goyal on 19/12/15.
 */
public enum ErrorCode {
    TABLE_INITIALIZATION_ERROR,
    STORE_CONNECTION_ERROR,
    DOCUMENT_NOT_FOUND,
    TABLE_METADATA_FETCH_FAILURE,
    DATA_CLEANUP_FAILURE,
    MALFORMED_QUERY,
    ACTION_RESOLUTION_FAILURE,
    UNRESOLVABLE_OPERATION,
    TABLE_NOT_FOUND,
    INVALID_REQUEST,
    STORE_EXECUTION_ERROR,
    DATA_CLEANUP_ERROR,
    QUERY_EXECUTION_ERROR,
    MALFORMED_QUERY_ERROR,
    TABLE_ALREADY_EXISTS,
    EXECUTION_EXCEPTION,
    CONSOLE_SAVE_EXCEPTION,
    CONSOLE_FETCH_EXCEPTION
}
